/*
Created: 3/14/2019
Modified: 4/10/2019
Model: GENOM_PORTABLE
Database: SQLite 3.7
*/


-- Create tables section -------------------------------------------------

-- Table GENOM_SAMPLE

CREATE TABLE "GENOM_SAMPLE"
(
  "sample_id" "NVARCHAR"(4000) NOT NULL COLLATE NOCASE,
  "normal_sample_id" "NVARCHAR"(4000),
  "pipeline_log" "BLOB",
  "pat_id" "NVARCHAR"(4000),
  "pat_sex" "NVARCHAR"(4000),
  "date_processed" "DATETIME",
  CONSTRAINT "PK_GENOM_SAMPLE" PRIMARY KEY ("sample_id") ON CONFLICT ROLLBACK
);

-- Table GENOM_DEPTH

CREATE TABLE "GENOM_DEPTH"
(
  "depth_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_DEPTH" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "chrom" "NVARCHAR"(50) COLLATE NOCASE,
  "start" "INT" COLLATE NOCASE,
  "end" "INT" COLLATE NOCASE,
  "id" "NVARCHAR"(4000) COLLATE NOCASE,
  "normal_mean" "NUMERIC"(38, 10) COLLATE NOCASE,
  "tumor_mean" "NUMERIC"(38, 10) COLLATE NOCASE,
  "tumor_depth" "NVARCHAR"(4000) COLLATE NOCASE,
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_DEPTH" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_DEPTH_sample_id" ON "GENOM_DEPTH" ("sample_id");

-- Table GENOM_ERROR_LOG

CREATE TABLE "GENOM_ERROR_LOG"
(
  "log_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_ERROR_LOG" PRIMARY KEY AUTOINCREMENT,
  "log_date" "DATETIME" NOT NULL,
  "error_type" "NVARCHAR"(4000) COLLATE NOCASE,
  "error_msg" "NVARCHAR"(4000)
);

-- Table GENOM_STRUCTVAR

CREATE TABLE "GENOM_STRUCTVAR"
(
  "sv_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_STRUCTVAR" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "sv_tool" "NVARCHAR"(4000),
  "chrom" "NVARCHAR"(4000) COLLATE NOCASE,
  "pos" "NVARCHAR"(4000) COLLATE NOCASE,
  "id" "NVARCHAR"(4000) COLLATE NOCASE,
  "ref" "NVARCHAR"(4000) COLLATE NOCASE,
  "alt" "NVARCHAR"(4000) COLLATE NOCASE,
  "qual" "NVARCHAR"(4000) COLLATE NOCASE,
  "filter" "NVARCHAR"(4000) COLLATE NOCASE,
  "info" "NVARCHAR"(4000) COLLATE NOCASE,
  "format" "NVARCHAR"(4000) COLLATE NOCASE,
  "normal" "NVARCHAR"(4000) COLLATE NOCASE,
  "tumor" "NVARCHAR"(4000) COLLATE NOCASE,
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_STRUCTVAR" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_STRUCTVAR_sample_id" ON "GENOM_STRUCTVAR" ("sample_id");

-- Table GENOM_MUTATIONS

CREATE TABLE "GENOM_MUTATIONS"
(
  "mut_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_MUTATIONS" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "mut_tool" "NVARCHAR"(4000),
  "chrom" "NVARCHAR"(4000) COLLATE NOCASE,
  "pos" "NVARCHAR"(4000) COLLATE NOCASE,
  "id" "NVARCHAR"(4000) COLLATE NOCASE,
  "ref" "NVARCHAR"(4000) COLLATE NOCASE,
  "alt" "NVARCHAR"(4000) COLLATE NOCASE,
  "qual" "NVARCHAR"(4000) COLLATE NOCASE,
  "filter" "NVARCHAR"(4000) COLLATE NOCASE,
  "info" "NVARCHAR"(4000) COLLATE NOCASE,
  "format" "NVARCHAR"(4000) COLLATE NOCASE,
  "normal" "NVARCHAR"(4000) COLLATE NOCASE,
  "tumor" "NVARCHAR"(4000) COLLATE NOCASE,
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_MUTATIONS" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_MUTATIONS_sample_id" ON "GENOM_MUTATIONS" ("sample_id");

-- Table GENOM_METRICS

CREATE TABLE "GENOM_METRICS"
(
  "metrics_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_METRICS" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "type" "NVARCHAR"(4000) COLLATE NOCASE,
  "bait_set" "NVARCHAR"(4000) COLLATE NOCASE,
  "genome_size" "NVARCHAR"(4000) COLLATE NOCASE,
  "bait_territory" "NVARCHAR"(4000) COLLATE NOCASE,
  "target_territory" "NVARCHAR"(4000) COLLATE NOCASE,
  "bait_design_efficiency" "NVARCHAR"(4000) COLLATE NOCASE,
  "total_reads" "NVARCHAR"(4000) COLLATE NOCASE,
  "pf_reads" "NVARCHAR"(4000) COLLATE NOCASE,
  "pf_unique_reads" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_pf_reads" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_pf_uq_reads" "NVARCHAR"(4000) COLLATE NOCASE,
  "pf_uq_reads_aligned" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_pf_uq_reads_aligned" "NVARCHAR"(4000) COLLATE NOCASE,
  "pf_bases_aligned" "NVARCHAR"(4000) COLLATE NOCASE,
  "pf_uq_bases_aligned" "NVARCHAR"(4000) COLLATE NOCASE,
  "on_bait_bases" "NVARCHAR"(4000) COLLATE NOCASE,
  "near_bait_bases" "NVARCHAR"(4000) COLLATE NOCASE,
  "off_bait_bases" "NVARCHAR"(4000) COLLATE NOCASE,
  "on_target_bases" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_selected_bases" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_off_bait" "NVARCHAR"(4000) COLLATE NOCASE,
  "on_bait_vs_selected" "NVARCHAR"(4000) COLLATE NOCASE,
  "mean_bait_coverage" "NVARCHAR"(4000) COLLATE NOCASE,
  "mean_target_coverage" "NVARCHAR"(4000) COLLATE NOCASE,
  "median_target_coverage" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_usable_bases_on_bait" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_usable_bases_on_target" "NVARCHAR"(4000) COLLATE NOCASE,
  "fold_enrichment" "NVARCHAR"(4000) COLLATE NOCASE,
  "zero_cvg_targets_pct" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_exc_dupe" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_exc_mapq" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_exc_baseq" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_exc_overlap" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_exc_off_target" "NVARCHAR"(4000) COLLATE NOCASE,
  "fold_80_base_penalty" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_1x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_2x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_10x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_20x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_30x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_40x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_50x" "NVARCHAR"(4000) COLLATE NOCASE,
  "pct_target_bases_100x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_library_size" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_10x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_20x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_30x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_40x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_50x" "NVARCHAR"(4000) COLLATE NOCASE,
  "hs_penalty_100x" "NVARCHAR"(4000) COLLATE NOCASE,
  "at_dropout" "NVARCHAR"(4000) COLLATE NOCASE,
  "gc_dropout" "NVARCHAR"(4000) COLLATE NOCASE,
  "het_snp_sensitivity" "NVARCHAR"(4000) COLLATE NOCASE,
  "het_snp_q" "NVARCHAR"(4000) COLLATE NOCASE,
  "sample" "NVARCHAR"(4000) COLLATE NOCASE,
  "library" "NVARCHAR"(4000) COLLATE NOCASE,
  "read_group" "NVARCHAR"(4000) COLLATE NOCASE,
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_METRICS" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_METRICS_sample_id" ON "GENOM_METRICS" ("sample_id");

-- Table GENOM_SNPDIFF

CREATE TABLE "GENOM_SNPDIFF"
(
  "snpdiff_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_SNPDIFF" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "chrom" "NVARCHAR"(4000) COLLATE NOCASE,
  "pos" "NVARCHAR"(4000) COLLATE NOCASE,
  "ncount" "NVARCHAR"(4000) COLLATE NOCASE,
  "nvaf" "NVARCHAR"(4000) COLLATE NOCASE,
  "tcount" "NVARCHAR"(4000) COLLATE NOCASE,
  "tvaf" "NVARCHAR"(4000) COLLATE NOCASE,
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_SNPDIFF" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_SNPDIFF_sample_id" ON "GENOM_SNPDIFF" ("sample_id");

-- Table GENOM_DB

CREATE TABLE "GENOM_DB"
(
  "db_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_DB" PRIMARY KEY AUTOINCREMENT,
  "ref_genome" "NVARCHAR"(4000),
  "pipeline_name" "NVARCHAR"(4000)
);

-- Table GENOM_FILES

CREATE TABLE "GENOM_FILES"
(
  "file_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_FILES" PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
  "sample_id" "NVARCHAR"(4000) NOT NULL ON CONFLICT ROLLBACK COLLATE NOCASE,
  "file_type" "NVARCHAR"(4000),
  "file_tool" "NVARCHAR"(4000),
  "file_header" "BLOB",
  "file_name" "NVARCHAR"(4000),
  "file_path" "NVARCHAR"(4000),
  CONSTRAINT "FK_GENOM_SAMPLE_GENOM_FILES" FOREIGN KEY ("sample_id") REFERENCES "GENOM_SAMPLE" ("sample_id")
);

CREATE INDEX "IX_GENOM_FILES_sample_id" ON "GENOM_FILES" ("sample_id");

-- Table GENOM_BEDFILES

CREATE TABLE "GENOM_BEDFILES"
(
  "bed_id" INTEGER NOT NULL
        CONSTRAINT "PK_GENOM_BEDFILES" PRIMARY KEY AUTOINCREMENT,
  "db_id" INTEGER,
  "chrom" "NVARCHAR"(4000),
  "start" "INT",
  "end" "INT",
  "id" "NVARCHAR"(4000),
  "type" "NVARCHAR"(4000),
  CONSTRAINT "FK_GENOM_DB_GENOM_BEDFILES" FOREIGN KEY ("db_id") REFERENCES "GENOM_DB" ("db_id")
);

